// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CerealDatabase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929111255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Cereal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("calories")
                        .HasColumnType("INTEGER");

                    b.Property<float>("carbo")
                        .HasColumnType("REAL");

                    b.Property<float>("cups")
                        .HasColumnType("REAL");

                    b.Property<int>("fat")
                        .HasColumnType("INTEGER");

                    b.Property<float>("fiber")
                        .HasColumnType("REAL");

                    b.Property<int>("mfr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("potass")
                        .HasColumnType("INTEGER");

                    b.Property<int>("protein")
                        .HasColumnType("INTEGER");

                    b.Property<float>("rating")
                        .HasColumnType("REAL");

                    b.Property<int>("shelf")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sodium")
                        .HasColumnType("INTEGER");

                    b.Property<int>("sugars")
                        .HasColumnType("INTEGER");

                    b.Property<int>("type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("vitamins")
                        .HasColumnType("INTEGER");

                    b.Property<float>("weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Cereals");
                });
#pragma warning restore 612, 618
        }
    }
}
